# Generated by Django 3.2 on 2021-05-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientapp',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=200)),
                ('prenom_client', models.CharField(max_length=200)),
                ('telephone_client', models.CharField(max_length=12)),
                ('adresse_client', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'clientapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compteclient',
            fields=[
                ('id_compteclient', models.IntegerField(primary_key=True, serialize=False)),
                ('email_client', models.CharField(max_length=200)),
                ('password_client', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'compteclient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id_domaine', models.IntegerField(primary_key=True, serialize=False)),
                ('label_domaine', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'domaine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id_prestataire', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prestataire', models.CharField(max_length=200)),
                ('prenom_prestataire', models.CharField(max_length=200)),
                ('adresse_prestataire', models.CharField(max_length=200)),
                ('site_web', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone_prestaire', models.CharField(max_length=12)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('desc_competences', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'prestataire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profilprestataire',
            fields=[
                ('id_profil', models.IntegerField(primary_key=True, serialize=False)),
                ('email_prestaire', models.CharField(max_length=150)),
                ('password_prestataire', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'profilprestataire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceapp',
            fields=[
                ('id_service', models.IntegerField(primary_key=True, serialize=False)),
                ('label_service', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'serviceapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceclient',
            fields=[
                ('id_service', models.OneToOneField(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='one4all.serviceapp')),
            ],
            options={
                'db_table': 'serviceclient',
                'managed': False,
            },
        ),
    ]
