# Generated by Django 3.2 on 2021-05-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one4all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicedemandee',
            fields=[
                ('id_service', models.OneToOneField(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='one4all.serviceapp')),
                ('date_demande', models.DateField(blank=True, null=True)),
                ('paye', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicedemandee',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Serviceclient',
        ),
    ]
